
networks:
  TREX-otp-server:

services:
  redis:
    build:
      context: ./redis_server
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - "${REDIS_HOST_DIR}:${REDIS_CONTAINER_DIR}"
    command: ["redis-server", "--requirepass", "${REDIS_PASS}", "--appendonly", "yes"]
    networks:
      - TREX-otp-server
  fastapi-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8001:8000"
    depends_on:
      - redis
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ${FASTAPI_LOG_HOST}:${FASTAPI_LOG_CONTAINER}
    networks:
      - TREX-otp-server